name: Build and Test DigiTemp

on:
  pull_request:
    branches:
      - master
  pull:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ds9097, ds9097u, ds2490]

    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v3
      - name: Build DigiTemp
        run: make ${matrix.target} && digitemp_* -T
